### ISSUE TITLE
burst service - istio

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/istio#31]
- does burst service need istio?
- since it's an internal service, we should be able to remove

## Description

What: 
 - 
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Acceptance Criteria

-
-
-

## Constraints
- N/A 

## References:
- References #https://github.com/retaildevcrews/wcnp/issues/313

**Comment by jofultz** [comment]
Burst Service is now deployed without the need for Istio.
