### ISSUE TITLE
HPA scale down

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/istio#35]
- it takes several minutes for HPA to scale back to one node
- can we make it faster?

## Description

What: 
 - 
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Acceptance Criteria

-
-
-

## Constraints
- N/A 

## References:
- References #

**Comment by dsturgell** [comment]
closing, reference https://github.com/retaildevcrews/wcnp/issues/674
